### ISSUE TITLE
REFlex isn't recording match history

### ISSUE THREAD

**Issue by pavenarius** [AcidWeb/REFlex#10]
As of the 8.2 patch, REFLex isn't recording my match history. I am on the latest version.

**Comment by AcidWeb** [comment]
Battlegrounds or arenas?

**Comment by pavenarius** [comment]
I haven't tried arenas since season end, so I'm not sure, but definitely not working for regular battlegrounds.

**Comment by AcidWeb** [comment]
Please execute `/console scriptErrors 1` and check if any LUA errors pop up at match end.
Also check if your season filter is not set to "Current season". Matches between seasons might don't have proper data.

I played multiple regular BGs after 8.2 and all were recorded.

**Comment by pavenarius** [comment]
That was it. Apologies for the confusion and thank you for your assistance!

**Comment by pavenarius** [comment]
I think I have to reopen this issue. I haven't seen any battlegrounds recorded this week, both before season 3 kicked off on Tuesday and after. Can you confirm that normal unrated battlegrounds are being recorded? Arenas are being recorded, but not BGs.

**Comment by AcidWeb** [comment]
They are. If recording failed you should see some LUA errors so make sure that reporting is enabled.

**Comment by pavenarius** [comment]
I do not understand. Yesterday I played battlegrounds across multiple characters, and today it is working again. Apologies, it must be another addon that's interfering.
