### ISSUE TITLE
"API returned corrupted data." error

### ISSUE THREAD

**Issue by juliarvalenti** [AcidWeb/REFlex#12]
![image](https://user-images.githubusercontent.com/42276144/103493341-adedb200-4dfe-11eb-965f-30a51a83fa10.png)

Seeing this pop up after a majority of games and most games are not being logged.

**Comment by AcidWeb** [comment]
I'm currently reviving some reports about this issue but can't replicate it locally and not found the cause yet.

**Comment by AcidWeb** [comment]
Please make a screenshot of arena scoreboard next time you see this error.
