### ISSUE TITLE
Error logging RBGs

### ISSUE THREAD

**Issue by xeropresence** [AcidWeb/REFlex#14]
REFlex\REFlex-3.0.2.lua:900: Usage: GetBattlefieldStatData(playerIndex, statIndex)
[string "=[C]"]: ?
[string "@REFlex\REFlex-3.0.2.lua"]:900: in function <REFlex\REFlex.lua:856>

Locals:
(*temporary) = nil
(*temporary) = 1

Strange is that this doesn't happen on all my characters, just some.

**Comment by AcidWeb** [comment]
It is issue reported by multiple people but all of them disappear after initial report.
Personally I can't replicate this on any character.

Replace `REFlex.lua` with this file: https://gist.githubusercontent.com/AcidWeb/f8b133e11e7d5ebe00f1e5c236be7d2f/raw/2854fbbd39dc4fd80e7777018f681fcf5fb74a51/REFlex.lua

Check if it fix the issue. If not please provide all debug messages that will appear in chat.
