### ISSUE TITLE
trying to change the LOW frame strata

### ISSUE THREAD

**Issue by keenanselbee** [AcidWeb/REFlex#18]
not a real issue because it's more of a personal problem, I just can't figure out how to change the strata level! It is LOW strata for me which is under some of my weakauras. I've looked and run some searches through all the code but I'm just not picking it out. Is it in the ace stuff somewhere? Any help would be greatly appreciated and others might be curious too.

**Comment by AcidWeb** [comment]
Change it here: https://github.com/AcidWeb/REFlex/blob/master/REFlex.xml#L11

**Comment by keenanselbee** [comment]
I hate to admit this but I can't figure it out. Do I change the parent?

**Comment by keenanselbee** [comment]
ahh I just add frameStrata="HIGH", of course. Thanks for the help!
