### ISSUE TITLE
9.1.5 Lua Error

### ISSUE THREAD

**Issue by Nukme** [AcidWeb/REFlex#19]
Can't review details.

58x ...rfaceREFlex\Libs\LibQTip-1.0\LibQTip-1.0.lua:543: attempt to call method 'GetBackdrop' (a nil value)
[string "@REFlex\Libs\LibQTip-1.0\LibQTip-1.0.lua"]:543: in function <...rfaceREFlex\Libs\LibQTip-1.0\LibQTip-1.0.lua:539>
[string "@REFlex\Libs\LibQTip-1.0\LibQTip-1.0.lua"]:132: in function `Acquire'
[string "@REFlex\REFlex-3.1.6.lua"]:257: in function `OnEnter'
[string "@Masque\Libs\LibDBIcon-1.0\LibDBIcon-1.0-44.lua"]:77: in function `oenter'
[string "@MBB\MBB-4.0.7.lua"]:486: in function <MBB\MBB.lua:468>

Locals:
tooltip = <unnamed> {
 0 = <userdata>
 scrollChild = <unnamed> {
 }
 scrollFrame = <unnamed> {
 }
}
key = "REFlexTooltipLDB"
(*temporary) = nil
(*temporary) = <unnamed> {
 0 = <userdata>
 SetCenterColor = <function> defined @SharedXML\NineSlice.lua:224
 GetFrameLayoutTextureKit = <function> defined @SharedXML\NineSlice.lua:213
 Center = <unnamed> {
 }
 GetBorderColor = <function> defined @SharedXML\NineSlice.lua:249
 TopRightCorner = <unnamed> {
 }
 TopLeftCorner = <unnamed> {
 }
 RightEdge = <unnamed> {
 }
 OnLoad = <function> defined @SharedXML\NineSlice.lua:217
 TopEdge = <unnamed> {
 }
 BottomEdge = <unnamed> {
 }
 GetCenterColor = <function> defined @SharedXML\NineSlice.lua:231
 SetBorderBlendMode = <function> defined @SharedXML\NineSlice.lua:261
 GetFrameLayoutType = <function> defined @SharedXML\NineSlice.lua:209
 BottomRightCorner = <unnamed> {
 }
 SetBorderColor = <function> defined @SharedXML\NineSlice.lua:238
 LeftEdge = <unnamed> {
 }
 BottomLeftCorner = <unnamed> {
 }
}
(*temporary) = "attempt to call method 'GetBackdrop' (a nil value)"
GameTooltip = GameTooltip {
 0 = <userdata>
 textLeft1Font = "GameTooltipHeaderText"
 ItemTooltip = <unnamed> {
 }
 SetHyperlink = <function> defined =[C]:-1
 SetGuildBankItem = <function> defined =[C]:-1
 updateTooltipTimer = 0.185000
 TextRight1 = GameTooltipTextRight1 {
 }
 textRight2Font = "GameTooltipText"
 comparing = false
 ClearLines = <function> defined =[C]:-1
 progressBarPool = <table> {
 }
 hasMoney = 1
 TopOverlay = <unnamed> {
 }
 default = 1
 SetUnitDebuff = <function> defined =[C]:-1
 SetItemByID = <function> defined =[C]:-1
 SetLootItem = <function> defined =[C]:-1
 SetQuestItem = <function> defined =[C]:-1
 Show = <function> defined =[C]:-1
 waitingForData = false
 FadeOut = <function> defined @TipTac\ttCore.lua:858
 numMoneyFrames = 1
 ttGradient = <unnamed> {
 }
 SetIconTextureAndText = <function> defined @TipTacItemRef\ttItemRef.lua:62
 SetRecipeReagentItem = <function> defined =[C]:-1
 SetBuybackItem = <function> defined =[C]:-1
 shoppingTooltips = <table> {
 }
 SetInboxItem = <function> defined =[C]:-1
 SetMerchantItem = <function> defined =[C]:-1
 SetQuestLogItem = <function> defined =[C]:-1
 layoutType = "TooltipDefaultLayout"
 BottomOverlay = <unnamed> {
 }
 TextLeft1 = GameTooltipTextLeft1 {
 }
 SetTradePlayerItem = <function> defined =[C]:-1
 textRight1Font = "GameTooltipHeaderText"
 ttIcon = <unnamed> {
 }
 SetUnitBuff = <function> defined =[C]:-1
 NineSlice = <unnamed> {
 }
 textLeft2Font = "GameTooltipText"
 SetSendMailItem = <function> defined =[C]:-1
 ttCount = <unnamed> {
 }
 SetLootRollItem = <function> defined =[C]:-1
 SetUnitAura = <function> defined =[C]:-1
 SetTradeTargetItem = <function> defined =[C]:-1
 SetInventoryItem = <function> defined =[C]:-1
 SetBagItem = <function> defined =[C]:-1
 needsReset = true
 TextRight2 = GameTooltipTextRight2 {
 }
 TextLeft2 = GameTooltipTextLeft2 {
 }
 __tamedCounts = false
 SetRecipeResultItem = <function> defined =[C]:-1
}
AcquireTable = <function> defined @REFlex\Libs\LibQTip-1.0\LibQTip-1.0.lua:519
labelProvider = <table> {
 cells = <table> {
 }
 cellMetatable = <table> {
 }
 cellPrototype = <table> {
 }
 heap = <table> {
 }
}
CELL_MARGIN_H = 6
CELL_MARGIN_V = 3
ResetTooltipSize = <function> defined @REFlex\Libs\LibQTip-1.0\LibQTip-1.0.lua:865

**Comment by AcidWeb** [comment]
I will push one more update soon.
