### ISSUE TITLE
Our and Enemy Ratings

### ISSUE THREAD

**Issue by VolviX** [AcidWeb/REFlex#2]
Is it possible to see what were mine and enemy team ratings individually on extended tooltips? I mean like everyone ratings individually.

**Comment by AcidWeb** [comment]
You talking about arena or rated bgs?

**Comment by VolviX** [comment]
Everyones rating in rbgs but to be honest arenas would be good as well.

**Comment by AcidWeb** [comment]
Arena API don't provide extract values for separate players - only change. So can't collect and show that data.
Battleground one is. All values were collected - just not displayed.

I will add it in next release.
