### ISSUE TITLE
Question on how to determine if an arena is a win/loss.

### ISSUE THREAD

**Issue by aza547** [AcidWeb/REFlex#22]
Hi - hope you don't mind the question as it's not strictly related to your addon.

I'm writing a desktop app to record arena games programmatically by watching the combat log but I'm struggling to work out who has won an arena game from the combatlog. Wondered if you could point me in the right direction as I figure it's a problem you have solved!

Weirdly I expected the ARENA_MATCH_START / ARENA_MATCH_END to give this information. However this is from a game I won:

6/5 16:01:41.522  ARENA_MATCH_START,1672,32,3v3,1
6/5 16:02:55.609  ARENA_MATCH_END,0,74,2016,2010

To me it looks like the trailing on the first line "1" is my teamID, and the "0" on the second line is the winning team - implying it was a loss for me, but it was not - I am certain of it! [Reference](https://wowpedia.fandom.com/wiki/COMBAT_LOG_EVENT).

I had a quick search of the REFlex code and saw it appears you check for a PVP_MATCH_COMPLETE which looks to have similar information. However I don't have such events in my combatlog file. Best guess is that this is only available ingame. 

Thanks in advance for any input.

**Comment by AcidWeb** [comment]
Hi,

Never parsed combat logs of arena match. Is `teamID` always 1? it might be remnant of team systems.
