### ISSUE TITLE
Wrong sum lost rounds in solo arenas

### ISSUE THREAD

**Issue by CptShooter** [AcidWeb/REFlex#26]
I don't know if it's intentional or a bug, but addon can't sum lost rounds in solo ranked arenas.
![image](https://user-images.githubusercontent.com/1506567/209362509-3439bd19-af91-47f9-a46e-18a7f0693729.png)

**Comment by AcidWeb** [comment]
Duplicate of #25.

Currently I can't test proper way to detect how many rounds were played during one match. So I rather ignore them than count rounds that did not take place as loses.
