### ISSUE TITLE
REFlex has been blocked from an action only available to the Blizzard UI

### ISSUE THREAD

**Issue by emiljannesson** [AcidWeb/REFlex#27]
This is happening constantly when I close the Options window in the game. Once it starts happening it will happen every time I close the options until I reload but it doesn't seem to happen right away after logging in/reloading so not sure what triggers it.

From Bugsack:
```
20x [ADDON_ACTION_FORBIDDEN] AddOn 'REFlex' tried to call the protected function 'SpellStopCasting()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SpellStopCasting'
[string "@FrameXML/UIParent.lua"]:4052: in function `ToggleGameMenu'
[string "@SharedXML/Settings/Blizzard_SettingsPanel.lua"]:336: in function `TransitionBackOpeningPanel'
[string "@SharedXML/Settings/Blizzard_SettingsPanel.lua"]:325: in function `ExitWithCommit'
[string "@SharedXML/Settings/Blizzard_SettingsPanel.lua"]:301: in function `Close'
[string "@FrameXML/UIParent.lua"]:4030: in function `ToggleGameMenu'
[string "TOGGLEGAMEMENU"]:1: in function <[string "TOGGLEGAMEMENU"]:1>
```

**Comment by RaphanW** [comment]
I had a similar error, I'm sorry I didn't bugsack it. No error unless you open then close REFlex, then it won't let me hit action bars until reload.

Will come back with a bugsack report if I remember.

**Comment by AcidWeb** [comment]
This is not REFlex related. Starting from 10.0 settings was jus a taint factory. It should be better now.

**Comment by AcidWeb** [comment]
3.3.7 should improve this situation a little.
