### ISSUE TITLE
Recording RBG team compositions

### ISSUE THREAD

**Issue by nozzlegear** [AcidWeb/REFlex#31]
Hey, I run an RBG team that's been going twice per week since BFA. We've been using REFlex for almost as long to record our wins and losses. One thing I've been interested in getting more insight on is how our W/L rate changes with our team composition and our enemy team's composition. 

For example, do we win more over X period of time when we run demon hunter flag carriers or druid flag carriers; do we lose more often on Kotmogu when the enemy team has two healers or three healers, etc. It's hard to get that information from just a few RBGs, but with our team's consistency I think it'd be an interesting data point.

How feasible would it be for REFlex to record that information and export it with its CSV export? If it's a feature you're interested in adding, I'd be happy to start working on a pull request.

**Comment by AcidWeb** [comment]
Team compositions are already saved. Hold **Shift + Alt** to display extended tooltips.

For such extended analytic I would suggest to parse REFlex DB outside the game. Find `REFlex.lua` in your WTF directory. And parse `REFlexDatabase` dictionary there with your favorite programming language. You are interested in records where field `isRated` is true and `isArena` is not.

**Comment by nozzlegear** [comment]
Oh cool, can't believe I missed that after all this time. Thanks a ton. I'll get started writing a parser and post a link here once I'm done, for anyone who might be interested in how I did it in the future.
