### ISSUE TITLE
Menus work fine, but the addon doesn't show after 2v2 and doesn't show history

### ISSUE THREAD

**Issue by wrightling** [AcidWeb/REFlex#6]
I play a rogue in a disc/rogue team for 2v2 in BFA. AFter installing, I did probably 80 matches last night (rated).

Nothing popped up after each match summarizing, and when I click the minimap icon (left click) to bring up the window, it still shows "0 - 0" at the top and nothing below. I hadn't changed default setting of "3" for the arena comp statistics limit (nor any other setting).

In case useful, here are my other addons:

![image](https://user-images.githubusercontent.com/1406395/49123440-d301b500-f275-11e8-86ba-bb63d73070af.png)

![image](https://user-images.githubusercontent.com/1406395/49123463-e90f7580-f275-11e8-85ba-014d61825333.png)

![image](https://user-images.githubusercontent.com/1406395/49123484-f9275500-f275-11e8-805e-b66a00d3a939.png)

![image](https://user-images.githubusercontent.com/1406395/49123499-05abad80-f276-11e8-992c-7bdb407a3d27.png)

**Comment by AcidWeb** [comment]
Check tabs on bottom of the window. You probably looking on battleground stats.

Otherwise find REFlex.lua in your WTF directory and upload it somewhere.

**Comment by wrightling** [comment]
I will take a look tonight and close this ticket if that solves the problem (and apologize for not looking hard enough apparently) :P

**Comment by wrightling** [comment]
Your suggestion was correct - I hadn't noticed that you had to choose between Battleground and Arena views. Thanks!
